# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BurnFit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BurnFit

  target 'BurnFitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end

end
